Publication/ViewModels/PublicationCartViewModel.cs
using Publication.Data.models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Publication.ViewModels
{
    public class PublicationCartViewModel
    {
        public PublicationCart PublicationCart { get; set; }
        public string CurrentText { get; set; }
    }
}

Publication/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Publication.Data.interfaces;
using Publication.Data.models;
using Publication.ViewModels;

namespace Publication.Controllers
{
    public class ItemController : Controller
    {
        private readonly IGetBooks _getBooks;

        public ItemController(IGetBooks getBooks)
        {
            _getBooks = getBooks;
        }

        public IActionResult OpenItem(int bookId)
        {
            return View(new BookViewModel
            {
                Book = _getBooks.GetBookById(bookId),
                CurrentText = "Книга:"
            });
        }
    }
}

Publication/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Publication.Data.interfaces;
using Publication.Data.models;
using Publication.ViewModels;

namespace Publication.Controllers
{
    public class OrderController : Controller
    {
        private readonly IAllOrders _allOrders;
        private readonly PublicationCart _publicationCart;

        public OrderController(IAllOrders allOrders, PublicationCart publicationCart)
        {
            _allOrders = allOrders;
            _publicationCart = publicationCart;
        }

        public IActionResult Checkout()
        {
            _publicationCart.listPublicationItems = _publicationCart.GetPublicationItems();

            int totalValue = 0;
            foreach (var el in _publicationCart.listPublicationItems)
            {
                totalValue += el.Price;
            }

            return View(new OrderViewModel
            {
                PublicationCart = _publicationCart,
                TotalValue = totalValue
            });
        }

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            _publicationCart.listPublicationItems = _publicationCart.GetPublicationItems();

            int totalValue = 0;
            foreach (var el in _publicationCart.listPublicationItems)
            {
                totalValue += el.Price;
            }

            if (_publicationCart.listPublicationItems.Count == 0)
            {
                ModelState.AddModelError("", "Корзина пуста!");
            }

            if (ModelState.IsValid)
            {
                _allOrders.CreateOrder(order);
                return RedirectToAction("Complete");
            }

            return View(new OrderViewModel
            {
                Order = order,
                PublicationCart = _publicationCart,
                TotalValue = totalValue
            });
        }

        public IActionResult Complete()
        {
            return View();
        }
    }
}

Publication/Controllers/PublicationCartController.cs
using Microsoft.AspNetCore.Mvc;
using Publication.Data.interfaces;
using Publication.Data.models;
using Publication.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Publication.Controllers
{
    public class PublicationCartController : Controller
    {
        private readonly IGetBooks _bookRepository;
        private readonly PublicationCart _publicationCart;

        public PublicationCartController(IGetBooks bookRepository, PublicationCart publicationCart)
        {
            _bookRepository = bookRepository;
            _publicationCart = publicationCart;
        }

        public ViewResult Index()
        {
            _publicationCart.listPublicationItems = _publicationCart.GetPublicationItems();

            return View(new PublicationCartViewModel
            {
                PublicationCart = _publicationCart,
                CurrentText = (_publicationCart.listPublicationItems.Count == 0) ? "Ваша корзина пуста" : "Ваша корзина:"
            });
        }

        public RedirectToActionResult AddToCart(int id)
        {
            var item = _bookRepository.GetBookById(id);

            if(item != null)
            {
                _publicationCart.AddToCart(item);
            }

            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromCart(int id)
        {
            var item = _bookRepository.GetBookById(id);

            if (item != null)
            {
                _publicationCart.RemoveFromCart(item);
            }

            return RedirectToAction("Index");
        }
    }
}

Publication/Views/PublicationCart/Index.cshtml
@model PublicationCartViewModel

<div class="list-block publication-cart">
    <div class="container">
        <div class="d-flex justify-content-center">
            <div class="card">
                <div class="card-header">
                    <i class="fas fa-shopping-cart fa-2x d-inline-block"></i>
                    <h3 class="d-inline-block"> @Model.CurrentText</h3>
                </div>
                <div class="card-body list-group">
                    @foreach (var el in Model.PublicationCart.listPublicationItems)
                    {
                        <div class="list-group-item list-group-item-action alert-warning mb-2">
                            <a class="item" asp-controller="Item" asp-action="OpenItem" asp-route-bookId="@el.Book.Id">
                                <p><b>Книга:</b> @el.Book.Name</p>
                                <p><b>Ціна:</b> @string.Format("{0:C}", el.Book.Price)</p>
                                <a class="x-button" asp-controller="PublicationCart" asp-action="RemoveFromCart" asp-route-id="@el.Book.Id"><i class="fa fa-trash-alt" aria-hidden="true"></i></a>
                            </a>
                        </div>
                    }
                    <a class="btn btn-danger" asp-controller="Order" asp-action="Checkout">
                        Оплатити
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>